config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :movies do
    member do
      post :join
      post :quit
    end

    resources :reviews
  end

  namespace :account do
    resources :movies
    resources :reviews
  end
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  #validates :title, :description, presence: true
  belongs_to :user
  has_many :reviews
  validates_presence_of :title, :description
  has_many :movie_relationships
  has_many :members, through: :movie_relationships, source: :user
end

app/models/movie_relationship.rb
class MovieRelationship < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates_presence_of :content

  scope :recent, -> {order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :movies
  has_many :movie_relationships
  has_many :participated_movies, :through => :movie_relationships, :source => :movie

  def is_member_of?(movie)
    participated_movies.include?(movie)
  end

  def join!(movie)
    participated_movies << movie
  end

  def quit!(movie)
    participated_movies.delete(movie)
  end
end

app/controllers/account/movies_controller.rb
class Account::MoviesController < ApplicationController
  before_action :authenticate_user!

  def index
    @movies = current_user.participated_movies
  end
end

app/controllers/account/reviews_controller.rb
class Account::ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = current_user.reviews
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :join, :quit]
  before_action :find_movie_and_check_permission, only: [:edit, :update, :destroy]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user

    if @movie.save
      current_user.join!(@movie)
      redirect_to movies_path
    else
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = @movie.reviews.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def edit
  end

  def update

    if @movie.update(movie_params)
      redirect_to movies_path
      flash[:notice] = "你真牛！电影编辑成功！！！"
    else
      render :edit
    end
  end

  def destroy

    @movie.destroy
      redirect_to movies_path
      flash[:alert] = "已被成功删除《"+@movie.title+"》！！！"
  end

  def join
    @movie = Movie.find(params[:id])

    if !current_user.is_member_of?(@movie)
      current_user.join!(@movie)
      flash[:notice] = "收藏电影《"+@movie.title+"》成功！"
    else
      flash[:warning] = "你已经收藏了《"+@movie.title+"》!"
    end

    redirect_to movie_path(@movie)
  end

  def quit
    @movie = Movie.find(params[:id])

    if current_user.is_member_of?(@movie)
      current_user.quit!(@movie)
      flash[:alert] = "你已经取消收藏《"+@movie.title+"》！！！"
    else
      flash[:warning] = "你未收藏《"+@movie.title+"》，怎么退出 XD"
    end

    redirect_to movie_path(@movie)
  end

  private

  def find_movie_and_check_permission
    @movie = Movie.find(params[:id])

    if current_user != @movie.user
      redirect_to movies_path
      flash[:alert] = "抱歉啦，你没有这个操作权限！！！"
    end
  end

  def movie_params
    params.require(:movie).permit(:title, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]

  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.movie = @movie
    @review.user = current_user

    if @review.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to account_reviews_path
      flash[:notice] = "编辑成功！"
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to account_reviews_path
    flash[:alert] = "你已成功删除影评！！！"
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] ="欢迎来影评！！！"
  end
end

app/helpers/account/movies_helper.rb
module Account::MoviesHelper
end

app/helpers/account/reviews_helper.rb
module Account::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def render_movie_description(movie)
    simple_format(movie.description)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flash.html.erb
<% if flash.any? %>
  <% user_faxing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2016 Movie Review
    <br>
    Design by<body>
      <a href="http://zhubaocheng-blog.logdown.com/">Tommy</a>
    </body>
  </p>
</footer>

app/views/common/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-inverse row" style="background-color: #1ECD97; border-color: #1ECD97;" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" style="color: #ffffff;" href="/">MovieReview</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right" >
          <% if !current_user %>
            <li><%= link_to("注册", new_user_registration_path) %></li>
            <li><%= link_to("登录", new_user_session_path) %></li>
          <% else %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                你好！, <%= current_user.email %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <li><%= link_to("我收藏的电影", account_movies_path)%></li>
                  <li><%= link_to("我发表的影评", account_reviews_path)%></li>
                  <li class="divider"></li>
                  <li><%= link_to("退出", destroy_user_session_path, method: :delete) %></li>
                </li>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
      <%= yield %>
    </div>

    <%= render "common/footer" %>

  </body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :description, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "提交", class: "btn btn-default", data: { disable_with: "Submiting..."} %>
<% end %>

app/views/movies/_movie_item.html.erb
<% @movies.each do |movie| %>
  <tr>
    <td><%= link_to(movie.title, movie_path(movie)) %></td>
    <td><%= simple_format(movie.description)%></td>
    <td><%= movie.user.email %></td>
    <td>
      <% if current_user && current_user == movie.user %>
      <%= link_to("编辑", edit_movie_path(movie), class: "btn btn-primary btn-sm") %>
      <%= link_to("删除", movie_path(movie), class: "btn btn-warning btn-sm",
                  method: :delete, data: { confirm: "你确定删除吗？" }) %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/movies/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2>编辑电影《<%= @movie.title %>》</h2>
  <hr>

  <%= render "form" %>
</div>

app/views/movies/index.html.erb
<div class=col-md-12>
  <div class="group">
    <%= link_to("添加新电影", new_movie_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <th> 电影名称 </th>
      <th> 简介 </th>
      <th> 创建者 </th>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= link_to(movie.title, movie_path(movie)) %></td>
          <td><%= render_movie_description(movie) %></td>
          <td><%= movie.user.email %></td>
          <td>
            <% if current_user && current_user == movie.user %>
            <%= link_to("编辑", edit_movie_path(movie), class: "btn btn-primary btn-sm") %>
            <%= link_to("删除", movie_path(movie), class: "btn btn-warning btn-sm",
                        method: :delete, data: { confirm: "你确定删除吗？" }) %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/movies/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2> 添加新电影 </h2>
  <hr>
  <%= render "form" %>
</div>

app/views/movies/show.html.erb
<div class="col-md-12">
    <div class="group">

      <span class="pull-right">
        <% if current_user && current_user.is_member_of?(@movie) %>
          <label class="label label-success"> 已收藏 </label>
            <%= link_to("取消收藏", quit_movie_path(@movie), method: :post, class: "btn btn-default")%>
        <% else %>
          <label class="label label-warning"> 未收藏 </label>
            <%= link_to("收藏", join_movie_path(@movie), method: :post, class: "btn btn-default")%>
        <% end %>
      </span>
      <% if current_user && current_user.is_member_of?(@movie) %>
          <%= link_to("发表影评", new_movie_review_path(@movie), class: "btn btn-default pull-right")%>
      <% end %>
      <% if current_user && current_user == @movie.user %>
          <%= link_to("编辑电影信息", edit_movie_path(@movie), class: "btn btn-primary pull-right") %>
      <% end %>
    </div>
    <h2><%= @movie.title %></h2>
    <p><%= @movie.description %></p>
    <p><%= @movie.created_at %></p>

    <table class="table table-hover">
      <thead>
        <tr>
          <th> 影评内容 </th>
          <th> 影评作者 </th>
          <th> 发表时间 </th>
        </tr>
      </thead>
      <tbody>
        <% @reviews.each do |review| %>
          <tr>
            <td><%= review.content %></td>
            <td><%= review.user.email %></td>
            <td><%= review.created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center">
        <%= will_paginate @reviews %>
    </div>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h2 class="text-center"> 编辑《<%= @movie.title %>》影评</h2>
  <%= simple_form_for [@movie, @review] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"}%>
    </div>
    <div class="form-actions">
      <%= f.submit "提交", disable_with: "Submiting...", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h2 class="text-center"> 新增《<%= @movie.title %>》影评 </h2>
<hr>
<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@movie, @review] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "提交", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1> Welcome to MovieReview! </h1>